language: java
sudo: false
addons:
    sonarcloud:
        organization: "bentobox-world"

jdk:
    - openjdk11
    
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=BentoBoxWorld_Limits
  
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'
